# Generated by Django 5.0.2 on 2024-02-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Char_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50)),
                ('hp', models.CharField(default='default', max_length=20)),
                ('atk', models.CharField(default='default', max_length=20)),
                ('df', models.CharField(default='default', max_length=20)),
                ('asc_rock', models.CharField(default='default', max_length=50)),
                ('asc_mat1', models.CharField(default='default', max_length=50)),
                ('asc_mat2', models.CharField(default='default', max_length=50)),
                ('boss_mat', models.CharField(default='default', max_length=50)),
                ('c1', models.CharField(default='default', max_length=1000)),
                ('c2', models.CharField(default='default', max_length=1000)),
                ('c3', models.CharField(default='default', max_length=1000)),
                ('c4', models.CharField(default='default', max_length=1000)),
                ('c5', models.CharField(default='default', max_length=1000)),
                ('c6', models.CharField(default='default', max_length=1000)),
            ],
        ),
    ]
