# Generated by Django 5.0.2 on 2024-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_char_detail_asc_mat3_char_detail_asc_mat4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='char_detail',
            name='f_name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
