# Generated by Django 5.0.2 on 2024-02-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_char_detail_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='char_detail',
            name='vision',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
